### ISSUE TITLE
Dear wu, class2sim is a very interesting research, but i have one questions for the transformation from s_ij to s-_ij as follows

### ISSUE THREAD

**Issue by LanXiaoPang613** [scifancier/Class2Simi#1]
Dear wu,
class2sim is a very interesting research, but i have one question for the transformation from s_ij to s-_ij, the question is added to the attachment, thank for your attention.
[1.docx](https://github.com/scifancier/Class2Simi/files/10547247/1.docx)

**Comment by scifancier** [comment]
Thanks for raising this issue. The T_s in the code is compatible with the S_ij. When calculating the \bar{S}_ij, as shown in line 17 in criterion.py `P = P * q[0][0] + (1 - P) * q[1][0]`, P is the similarity posterior and thereby q[0][0] is actually T[1][1]. That is why simi_T is calculated as shown in the code.

**Comment by scifancier** [comment]
Thanks for raising this issue. The T_s in the code is compatible with the S_ij. When calculating the \bar{S}_ij, as shown in line 17 in criterion.py `P = P * q[0][0] + (1 - P) * q[1][0]`, P is the similarity posterior and thereby q[0][0] is actually T[1][1]. That is why simi_T is calculated as shown in the code.

**Comment by LanXiaoPang613** [comment]
okok， i have understanded this equation, thank for your reply.
